# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# To test against all files, run:
# $ pre-commit run --all-files --hook-stage push

# Only run on pushing to remote branch so that you can have dirty commits
# during development.
default_stages: [push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.292
    hooks:
      - id: pyright
        entry: pyright --project py
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
